<a href="https://colab.research.google.com/github/Okta-S/tugas2/blob/main/processingdata.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Langkah Awal sebslum kita menjalankan preprocessingdata, kita harus menginport library seperti di bawah ini:

In [74]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Setelah mengimpor library, langkah berikutnya adalah membaca data dari file CSV yang berisi nilai X dan Y.

In [75]:
dataset = pd.read_csv('data_rumah_sakit.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

menjalankan printah untuk membaca nilai X

In [76]:
print(x)

[['RS Bhayangkara' 45.0 5200000.0]
 ['RSUD Gambiran' 29.0 3800000.0]
 ['RS Aura Syifa' nan 4900000.0]
 ['RS Baptis Kediri' 40.0 nan]
 ['RS Muhammadiyah Ahmad Dahlan' 40.0 6700000.0]
 ['RSUD Pare' 38.0 4200000.0]
 ['RS HVA Toeloengredjo' nan 5600000.0]
 ['RS Aura Syifa' 50.0 7300000.0]
 ['RSUD Gambiran' 42.0 8100000.0]
 ['RS Baptis Kediri' 37.0 6200000.0]]


menjalankan printah untuk membaca nilai y

In [77]:
print(y)

['Ya' 'Tidak' 'Ya' 'Tidak' 'Ya' 'Tidak' 'Ya' 'Tidak' 'Ya' 'Tidak']


Jika terdapat nilai yang hilang dalam dataset, kita akan mengisinya dengan nilai rata-rata (mean) dari masing-masing kolom.

In [78]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

Ketika kita menjalankan kode `print(X)`, program akan menampilkan data X setelah proses pengisian nilai yang hilang dengan rata-rata (mean). Ini berguna untuk memastikan bahwa semua nilai yang hilang telah terisi dengan benar dan dataset siap digunakan untuk analisis lebih lanjut.

In [79]:
print(x)

[['RS Bhayangkara' 45.0 5200000.0]
 ['RSUD Gambiran' 29.0 3800000.0]
 ['RS Aura Syifa' 40.125 4900000.0]
 ['RS Baptis Kediri' 40.0 5777777.777777778]
 ['RS Muhammadiyah Ahmad Dahlan' 40.0 6700000.0]
 ['RSUD Pare' 38.0 4200000.0]
 ['RS HVA Toeloengredjo' 40.125 5600000.0]
 ['RS Aura Syifa' 50.0 7300000.0]
 ['RSUD Gambiran' 42.0 8100000.0]
 ['RS Baptis Kediri' 37.0 6200000.0]]


Kita akan mengubah data kategorikal menjadi bentuk numerik menggunakan One-Hot Encoding. Metode ini akan mengonversi setiap kategori unik dalam kolom menjadi vektor biner, sehingga data lebih mudah diproses oleh algoritma machine learning.

In [80]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

Saat kita menjalankan `print(X)`, program akan menampilkan data X setelah dikonversi menggunakan One-Hot Encoding. Ini memungkinkan kita untuk melihat bagaimana data kategorikal telah diubah menjadi bentuk numerik dengan representasi vektor biner.

In [81]:
print(x)

[[0.0 0.0 1.0 0.0 0.0 0.0 0.0 45.0 5200000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 29.0 3800000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 40.125 4900000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 40.0 5777777.777777778]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 40.0 6700000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 38.0 4200000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 40.125 5600000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 50.0 7300000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 42.0 8100000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 37.0 6200000.0]]


Kita akan mengonversi data kategorikal menjadi bentuk numerik menggunakan Label Encoding. Metode ini menggantikan setiap kategori unik dengan angka tertentu, sehingga data dapat digunakan dalam pemrosesan machine learning.

In [82]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
y=le.fit_transform(y)

Saat kita menjalankan `print(y)`, program akan menampilkan data y setelah dikonversi menggunakan Label Encoding. Ini memungkinkan kita melihat bagaimana setiap kategori telah digantikan dengan nilai numerik.

In [83]:
print(y)

[1 0 1 0 1 0 1 0 1 0]


Kita akan membagi dataset menjadi data latih (training) dan data uji (testing) agar model machine learning dapat belajar dari data latih dan dievaluasi menggunakan data uji.


In [84]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

Saat kita menjalankan `print(X_train)`, program akan menampilkan data latih (training) setelah proses pembagian dataset. Data ini digunakan oleh model machine learning untuk belajar pola dari dataset.

In [85]:
print(x_train)

[[0.0 0.0 0.0 1.0 0.0 0.0 0.0 40.125 5600000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 40.0 6700000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 45.0 5200000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 40.0 5777777.777777778]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 29.0 3800000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 50.0 7300000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 42.0 8100000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 38.0 4200000.0]]


Saat kita menjalankan `print(X_test)`, program akan menampilkan data uji (testing) setelah proses pembagian dataset. Data ini digunakan untuk menguji kinerja model setelah dilatih.

In [86]:
print(x_test)

[[1.0 0.0 0.0 0.0 0.0 0.0 0.0 40.125 4900000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 37.0 6200000.0]]


Saat kita menjalankan `print(y_train)`, program akan menampilkan data latih (training) untuk variabel target (y). Data ini digunakan oleh model machine learning untuk belajar dan menemukan pola dari dataset.

In [87]:
print(y_train)

[1 1 1 0 0 0 1 0]


Saat kita menjalankan `print(y_test)`, program akan menampilkan data uji (testing) untuk variabel target (y). Data ini digunakan untuk mengukur seberapa baik model dapat memprediksi hasil berdasarkan data yang belum pernah dilihat sebelumnya.

In [88]:
print(y_test)

[1 0]


Kita akan menstandarisasi fitur numerik dalam dataset menggunakan **StandardScaler** dari `sklearn.preprocessing`. Metode ini mengubah data sehingga memiliki rata-rata 0 dan standar deviasi 1, sehingga model machine learning dapat bekerja lebih optimal.

In [89]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 4:] = sc.fit_transform(x_train[:, 4:])
x_test[:, 4:]= sc.transform(x_test[:, 4:])

Saat kita menjalankan `print(X_train)`, program akan menampilkan data latih (training) setelah proses standarisasi. Data ini telah diubah sehingga memiliki rata-rata 0 dan standar deviasi 1, membantu model machine learning bekerja lebih optimal.

In [90]:
print(x_train)

[[0.0 0.0 0.0 1.0 -0.3779644730092272 -0.5773502691896258
  -0.3779644730092272 -0.06961466056901107 -0.16972328946661241]
 [0.0 0.0 0.0 0.0 2.6457513110645903 -0.5773502691896258
  -0.3779644730092272 -0.09189135195109462 0.6256663274420098]
 [0.0 0.0 1.0 0.0 -0.3779644730092272 -0.5773502691896258
  -0.3779644730092272 0.7991763033322471 -0.4589558774333841]
 [0.0 1.0 0.0 0.0 -0.3779644730092272 -0.5773502691896258
  -0.3779644730092272 -0.09189135195109462 -0.041175472592491505]
 [0.0 0.0 0.0 0.0 -0.3779644730092272 1.7320508075688774
  -0.3779644730092272 -2.0522401935744465 -1.471269935317085]
 [1.0 0.0 0.0 0.0 -0.3779644730092272 -0.5773502691896258
  -0.3779644730092272 1.6902439586155888 1.0595152093921674]
 [0.0 0.0 0.0 0.0 -0.3779644730092272 1.7320508075688774
  -0.3779644730092272 0.2645357101622421 1.6379803853257107]
 [0.0 0.0 0.0 0.0 -0.3779644730092272 -0.5773502691896258
  2.6457513110645903 -0.4483184140644313 -1.1820373473503134]]
